player_manager.AddValidModel( "Barney (HLS)", 					"models/player/hl1/Barney.mdl" )
player_manager.AddValidModel( "Gman (HLS)", 					"models/player/hl1/Gman.mdl" )
player_manager.AddValidModel( "Human Assassin (HLS)", 			"models/player/hl1/hassassin.mdl" )
player_manager.AddValidModel( "Human Assault (HLS)",			"models/player/hl1/hassault.mdl" )
player_manager.AddValidModel( "Helmet (HLS)", 					"models/player/hl1/Helmet.mdl" )
player_manager.AddValidModel( "Hgrunt (HLS)", 					"models/player/hl1/Hgrunt.mdl" )
player_manager.AddValidModel( "Hgrunt (black)(HLS)", 			"models/player/hl1/Hgrunt_black.mdl" )
player_manager.AddValidModel( "Hgrunt (cigar)(HLS)", 			"models/player/hl1/Hgrunt_cigar.mdl" )
player_manager.AddValidModel( "Hgrunt (Commander(HLS)", 		"models/player/hl1/Hgrunt_commander.mdl" )
player_manager.AddValidModel( "Hgrunt (shotgun)(HLS)", 			"models/player/hl1/Hgrunt_shotgun.mdl" )
player_manager.AddValidModel( "Hgrunt (shotgun black)(HLS)",	"models/player/hl1/Hgrunt_shotgun_black.mdl" )
player_manager.AddValidModel( "Holo (HLS)", 					"models/player/hl1/Holo.mdl" )
player_manager.AddValidModel( "Player (HLS)", 					"models/player/hl1/player.mdl" )
player_manager.AddValidModel( "Rgrunt (HLS)", 					"models/player/hl1/rgrunt.mdl" )
player_manager.AddValidModel( "Scientist (Einstien)(HLS)", 		"models/player/hl1/Scientist_einstien.mdl" )
player_manager.AddValidModel( "Scientist (Luther)(HLS)", 		"models/player/hl1/Scientist_luther.mdl" )
player_manager.AddValidModel( "Scientist (Slick)(HLS)", 		"models/player/hl1/Scientist_slick.mdl" )
player_manager.AddValidModel( "Scientist (Walter)(HLS)", 		"models/player/hl1/Scientist_walter.mdl" )
player_manager.AddValidModel( "Skeleton (HLS)", 				"models/player/hl1/Skeleton.mdl" )
player_manager.AddValidModel( "Zombie (HLS)", 					"models/player/hl1/zombie.mdl" )